---
title: "Tutorial Week 6 — Difference-in-Differences and Diagnostics"
subtitle: "SDS200 — Causal Inference"
output:
  pdf_document:
    latex_engine: pdflatex
    toc: false
    number_sections: false
    highlight: tango
fontsize: 11pt
geometry: margin=1in
header-includes:
  - \usepackage{setspace}
  - \setstretch{1.2}
  - \usepackage{parskip}
  - \usepackage{booktabs}
  - \usepackage{caption}
  - \captionsetup{labelfont=bf}
  - \usepackage{amsmath,amssymb}
  - \usepackage{microtype}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhf{}
  - \lhead{DS200 — Causal Inference}
  - \chead{Tutorial 6}
  - \rhead{Daniel Lehmann}
  - \renewcommand{\headrulewidth}{0.4pt}
  - \cfoot{\thepage}
  - \fancypagestyle{plain}{\fancyhf{}\lhead{SDS200 — Causal Inference}\chead{Tutorial Week 6}\rhead{Daniel Lehmann}\renewcommand{\headrulewidth}{0.4pt}\cfoot{\thepage}}
---




```{r setup, include=FALSE}

knitr::opts_chunk$set(
  echo = TRUE, message = FALSE, warning = FALSE,
  fig.align = "center", fig.width = 6, fig.height = 4
)

library(tidyverse)
library(janitor)
library(kableExtra)
library(scales)
library(modelsummary)
library(patchwork)
library(here)

theme_set(theme_minimal(base_size = 11))


```


# Q1: Setup and Data Construction

## 1) Read in the dataset and subset it to the years 1991, 1992, 1993 and 1996, 1997, 1998

```{r Load Data}

# Load data ("data00_AngristKugler.tab")
data <- read.delim(here("data00_AngristKugler.tab"))

# Create variable grow for further analysis

department_list <- c(13, 18, 19, 50, 52, 86, 95, 97, 99)

data <- data %>% 
  mutate(grow = ifelse(dep_ocu %in% department_list, 1, 0))

# Subsetting the dataset to years 1991 - 1993 and 1996 - 1998
data_subset <- data %>% 
  filter(year %in% c(1991, 1992, 1993, 1996, 1997, 1998))



```
## 2) Create new variables

```{r Variable Mutation}

# We create a variable called after with 1 for years 1996 - 1998
data_subset <- data_subset %>% 
  mutate(after = ifelse(year %in% c(1996, 1997, 1998), 1, 0))

# Create variable growafter (grow x after)
data_subset <- data_subset %>% 
  mutate(growafter = grow * after)


```



