% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Rural Windfall or a New Resource Curse? Coca, Income, and Civil Conflict in Colombia},
  pdfauthor={Maximilian Birkle; Daniel Lehmann; Henry Lucas},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Rural Windfall or a New Resource Curse? Coca, Income, and Civil
Conflict in Colombia}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Based on Angrist \& Kugler (2008)}
\author{Maximilian Birkle \and Daniel Lehmann \and Henry Lucas}
\date{2025-10-25}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Q1. Setup and Data
Construction}\label{q1.-setup-and-data-construction}

\textbf{Tasks:}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Create \texttt{grow} variable (1 if \texttt{dep\_ocu}
  \(\in \{13, 18, 19, 50, 52, 86, 95, 97, 99\}\), 0 otherwise)
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Creating a new variable grow}
\NormalTok{department\_list }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{13}\NormalTok{, }\DecValTok{18}\NormalTok{, }\DecValTok{19}\NormalTok{, }\DecValTok{50}\NormalTok{, }\DecValTok{52}\NormalTok{, }\DecValTok{86}\NormalTok{, }\DecValTok{95}\NormalTok{, }\DecValTok{97}\NormalTok{, }\DecValTok{99}\NormalTok{)}

\NormalTok{dta }\OtherTok{\textless{}{-}}\NormalTok{ dta }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{grow =} \FunctionTok{ifelse}\NormalTok{(dep\_ocu }\SpecialCharTok{\%in\%}\NormalTok{ department\_list, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Subset data to years 1991, 1992, 1993 and 1996, 1997, 1998
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Subsetting the dataset to years 1991 {-} 1993 and 1996 {-} 1998}
\NormalTok{dta\_subset }\OtherTok{\textless{}{-}}\NormalTok{ dta }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(year }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\DecValTok{1991}\NormalTok{, }\DecValTok{1992}\NormalTok{, }\DecValTok{1993}\NormalTok{, }\DecValTok{1996}\NormalTok{, }\DecValTok{1997}\NormalTok{, }\DecValTok{1998}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Create \texttt{after} variable (1 if year
  \(\in \{1996, 1997, 1998\}\), 0 otherwise)
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# We create a variable called after with 1 for years 1996 {-} 1998}
\NormalTok{dta\_subset }\OtherTok{\textless{}{-}}\NormalTok{ dta\_subset }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{after =} \FunctionTok{ifelse}\NormalTok{(year }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\DecValTok{1996}\NormalTok{, }\DecValTok{1997}\NormalTok{, }\DecValTok{1998}\NormalTok{), }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Create \texttt{growafter} variable (\texttt{grow} \(\times\)
  \texttt{after})
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Creating growafter variable (grow * after)}
\NormalTok{dta\_subset }\OtherTok{\textless{}{-}}\NormalTok{ dta\_subset }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{growafter =}\NormalTok{ grow }\SpecialCharTok{*}\NormalTok{ after)}

\NormalTok{dta\_subset }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{count}\NormalTok{(grow, after, growafter)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 4 x 4
##    grow after growafter     n
##   <dbl> <dbl>     <dbl> <int>
## 1     0     0         0  2491
## 2     0     1         0  2566
## 3     1     0         0   852
## 4     1     1         1   907
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  Create outcome variable:
  \(\log\left(\frac{\text{populati}+1}{\text{violent}+1}\right)\)
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create outcome variable}

\NormalTok{dta\_subset }\OtherTok{\textless{}{-}}\NormalTok{ dta\_subset }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{outcome =} \FunctionTok{log}\NormalTok{((violent }\SpecialCharTok{+} \DecValTok{1}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ (populati }\SpecialCharTok{+} \DecValTok{1}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Q2. Visualizing Violence Before and
After}\label{q2.-visualizing-violence-before-and-after}

\textbf{Tasks:}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Create density plots for non-growing vs.~growing regions, before
  vs.~after
\item
  Extend to \(2 \times 2\) grid by gender (men: \texttt{sex=1}, women:
  \texttt{sex=2})
\item
  Interpret: Evidence of shifts in violence? Different by gender?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Density plots: Non{-}growing vs. Growing regions}

\NormalTok{density\_plot }\OtherTok{\textless{}{-}}\NormalTok{ dta\_subset }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{period =} \FunctionTok{factor}\NormalTok{(after, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{), }\AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Before (1991{-}93)"}\NormalTok{, }\StringTok{"After (1996{-}98)"}\NormalTok{)),}
    \AttributeTok{region\_type =} \FunctionTok{factor}\NormalTok{(grow, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{), }\AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Non{-}Growing Region"}\NormalTok{, }\StringTok{"Growing Region"}\NormalTok{)),}
    \AttributeTok{gender =} \FunctionTok{factor}\NormalTok{(sex, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{), }\AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Men"}\NormalTok{, }\StringTok{"Women"}\NormalTok{))}
\NormalTok{  )}


\NormalTok{density\_plot }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ outcome, }\AttributeTok{fill =}\NormalTok{ period, }\AttributeTok{color =}\NormalTok{ period)) }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{ region\_type) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Logged per{-}capita violent death rate distribution: Before vs After by Region Type"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Number of Violent Deaths"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Density"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Tutorial-Week-6_files/figure-latex/q2-density-plots-simple-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 2x2 grid: Top=men, Bottom=women; Left=non{-}growing, Right=growing}

\NormalTok{density\_plot }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(gender)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ outcome, }\AttributeTok{fill =}\NormalTok{ period, }\AttributeTok{color =}\NormalTok{ period)) }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{facet\_grid}\NormalTok{(gender }\SpecialCharTok{\textasciitilde{}}\NormalTok{ region\_type) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Logged per{-}capita violent death rate distribution by Gender and Region Type"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Number of Violent Deaths"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Density"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Tutorial-Week-6_files/figure-latex/q2-density-plots-gender-1.pdf}}

\textbf{Interpretation:}

The evidence indicates a significant shift in violence following the
air-bridge disruption, with the effect being highly specific to both
region and gender. For the treatment group (\textbf{coca-growing
regions}), there was a slight increase in the per-capita violent death
rate among men. In contrast, the control group (\textbf{non-growing
regions}) showed no meaningful change for either gender, which suggests
that the increase in violence was not due to a nationwide trend.
Furthermore, the pattern seems to be strongly gendered; the effect on
women in the treatment group was minimal compared to a much larger
effect on men. This suggests that the impact of the coca boom on
violence was almost exclusively concentrated among the male population,
who seem to have been the primary participants in the conflict.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Q3. Age-Specific Effects}\label{q3.-age-specific-effects}

\textbf{Task:} For coca-growing regions only, plot the change in outcome
(after - before) by age group.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calculate mean difference by age for growing regions only}

\NormalTok{age\_effects }\OtherTok{\textless{}{-}}\NormalTok{ dta\_subset }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(grow }\SpecialCharTok{==} \DecValTok{1}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(age, after) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{mean\_outcome =} \FunctionTok{mean}\NormalTok{(outcome, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pivot\_wider}\NormalTok{(}\AttributeTok{names\_from =}\NormalTok{ after, }\AttributeTok{values\_from =}\NormalTok{ mean\_outcome, }\AttributeTok{names\_prefix =} \StringTok{"period\_"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{change =}\NormalTok{ period\_1 }\SpecialCharTok{{-}}\NormalTok{ period\_0)}

\CommentTok{\# Plot age{-}specific effects}
\NormalTok{age\_effects }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ age, }\AttributeTok{y =}\NormalTok{ change)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{color =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{size =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{color =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{size =} \DecValTok{2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Change in Logged per{-}capita Violent Death Rate by Age (Coca{-}Growing Regions)"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Age"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Change in Outcome (After {-} Before)"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Tutorial-Week-6_files/figure-latex/q3-age-effects-1.pdf}}

\textbf{Interpretation:}

This plot illustrates how the average violence rate changes for each age
group by calculating the difference between the average violence rate
for an age group after the air-bridge disruption and the average
violence rate for that same group before the disruption. Clearly, the
plot shows that the effect varies dramatically across different age
groups, with a concentration in certain age brackets. The increase in
conflict and violence seems to have disproportionately affected
individuals of fighting age, as can be seen from the peaks in the graph
between the ages of 17 and 22. Additionally, younger adolescents around
the age of 10 seem to have been particularly involved in violent
activities, resulting in a much higher death rate after the air
disruption. However, it is important to note that, for a few age groups
--- especially those around 15 years old --- the rate of violence
decreased after the air disruption.

This seemingly volatile distribution across age groups reveals a key
insight. If the increase in violence was solely due to increased
criminal activity, we would most likely see it concentrated among
cohorts that met the age of fighting and above. However, since we cleary
see that also much younger age groups show an increase in violent
deaths, we can conclude that this is mostly caused by conflict-related
violence (e.g.~civil war) after the `air bridge' intervention, which
corresponds to the paper's findings.

To explore this interesting trend, we created a graph for the per-capita
violent death rate in coca-growing regions before and after for men
only. What we can see here is that the increase in violence was not
confined by the typical ``fighting age'' bracket but was high across the
entire young male distribution, including children around 10. This
pattern strongly suggests widespread, conflict-related violence. The
coca boom fueled this by creating two distinct sets of victims: older
cohorts were recruited as soldiers, while younger boys, drawn in as
laborers, became collateral damage in the armed groups' fight to control
the coca fields and labor force. The overall increased death rate of
civillians may also have driven this trend.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{age\_effects\_men }\OtherTok{\textless{}{-}}\NormalTok{ dta\_subset }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(grow }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, sex }\SpecialCharTok{==} \DecValTok{1}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(age, after) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{mean\_outcome =} \FunctionTok{mean}\NormalTok{(outcome, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pivot\_wider}\NormalTok{(}
    \AttributeTok{names\_from =}\NormalTok{ after,}
    \AttributeTok{values\_from =}\NormalTok{ mean\_outcome,}
    \AttributeTok{names\_prefix =} \StringTok{"period\_"}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{change =}\NormalTok{ period\_1 }\SpecialCharTok{{-}}\NormalTok{ period\_0)}

\CommentTok{\# Plot for age specific effects}
\NormalTok{age\_effects\_men }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ age, }\AttributeTok{y =}\NormalTok{ change)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{color =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{size =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{color =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{size =} \DecValTok{2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_hline}\NormalTok{(}
    \AttributeTok{yintercept =} \DecValTok{0}\NormalTok{,}
    \AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{,}
    \AttributeTok{color =} \StringTok{"red"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Change in Logged per{-}capita Violent Death Rate by Age (Men in Coca{-}Growing Regions)"}\NormalTok{, }
    \AttributeTok{x =} \StringTok{"Age"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Change in Outcome (After {-} Before)"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Tutorial-Week-6_files/figure-latex/q3-men-age-effects-1.pdf}}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Q4. Testing the Parallel Trends Assumption
(Pre-Treatment)}\label{q4.-testing-the-parallel-trends-assumption-pre-treatment}

\textbf{Tasks:}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Use pre-treatment years (1990-1993)
\item
  Estimate: outcome
  \(= \alpha + \beta \cdot \text{year} + \gamma \cdot \text{grow} + \delta \cdot (\text{grow} \times \text{year}) + u\)
\item
  Test if \texttt{grow} \(\times\) \texttt{year} interactions are
  jointly zero (year as linear and categorical)
\item
  Create graph of average outcome by year and group
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Subset to pre{-}treatment years (1990{-}1993)}
\NormalTok{dta\_pretreatment }\OtherTok{\textless{}{-}}\NormalTok{ dta }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(year }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\DecValTok{1990}\NormalTok{, }\DecValTok{1991}\NormalTok{, }\DecValTok{1992}\NormalTok{, }\DecValTok{1993}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{grow =} \FunctionTok{ifelse}\NormalTok{(dep\_ocu }\SpecialCharTok{\%in\%}\NormalTok{ department\_list, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{),}
         \AttributeTok{outcome =} \FunctionTok{log}\NormalTok{((violent }\SpecialCharTok{+} \DecValTok{1}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ (populati }\SpecialCharTok{+} \DecValTok{1}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Model with year as linear}
\NormalTok{year\_linear }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(outcome }\SpecialCharTok{\textasciitilde{}}\NormalTok{ year }\SpecialCharTok{+}\NormalTok{ grow }\SpecialCharTok{+}\NormalTok{ year}\SpecialCharTok{:}\NormalTok{grow, }\AttributeTok{data =}\NormalTok{ dta\_pretreatment)}

\CommentTok{\# Model with year as categorical (factor)}
\NormalTok{year\_factor }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(outcome }\SpecialCharTok{\textasciitilde{}} \FunctionTok{factor}\NormalTok{(year) }\SpecialCharTok{+}\NormalTok{ grow }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(year)}\SpecialCharTok{:}\NormalTok{grow, }\AttributeTok{data =}\NormalTok{ dta\_pretreatment)}

\CommentTok{\# Stargazer table for better visualization}

\CommentTok{\# 1. Define the professional labels for your variables.}
\NormalTok{pro\_labels }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"Coca{-}Growing Region"}\NormalTok{,}
  \StringTok{"Year (Linear) $}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{times$ Growing Region"}\NormalTok{,}
  \StringTok{"1991 $}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{times$ Growing Region"}\NormalTok{,}
  \StringTok{"1992 $}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{times$ Growing Region"}\NormalTok{,}
  \StringTok{"1993 $}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{times$ Growing Region"}\NormalTok{,}
  \StringTok{"Constant"}
\NormalTok{)}

\CommentTok{\# 2. Run stargazer with new arguments}
\FunctionTok{stargazer}\NormalTok{(}
\NormalTok{  year\_linear, year\_factor,}
  \AttributeTok{type =} \StringTok{"latex"}\NormalTok{, }
  \AttributeTok{title =} \StringTok{"Table 1: Pre{-}Treatment Parallel Trends Test"}\NormalTok{,}
  \AttributeTok{header =} \ConstantTok{FALSE}\NormalTok{,}
  \AttributeTok{column.labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Linear Trend"}\NormalTok{, }\StringTok{"Categorical Trend"}\NormalTok{),}
  \AttributeTok{dep.var.labels =} \StringTok{"Logged Per{-}Capita Violent Death Rate"}\NormalTok{,}
  \AttributeTok{keep =} \FunctionTok{c}\NormalTok{(}\StringTok{"grow"}\NormalTok{, }\StringTok{"year:grow"}\NormalTok{, }\StringTok{"factor}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{(year}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{)199[1{-}3]:grow"}\NormalTok{, }\StringTok{"Constant"}\NormalTok{),}
  \AttributeTok{covariate.labels =}\NormalTok{ pro\_labels,}
  \AttributeTok{no.space =} \ConstantTok{TRUE}\NormalTok{,}
  \AttributeTok{omit.stat =} \FunctionTok{c}\NormalTok{(}\StringTok{"adj.rsq"}\NormalTok{, }\StringTok{"ser"}\NormalTok{,}\StringTok{"rsq"}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}[!htbp] \centering 
  \caption{Table 1: Pre-Treatment Parallel Trends Test} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}}lcc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{2}{c}{\textit{Dependent variable:}} \\ 
\cline{2-3} 
\\[-1.8ex] & \multicolumn{2}{c}{Logged Per-Capita Violent Death Rate} \\ 
 & Linear Trend & Categorical Trend \\ 
\\[-1.8ex] & (1) & (2)\\ 
\hline \\[-1.8ex] 
 Coca-Growing Region & 1.469 & 0.202$^{*}$ \\ 
  & (97.479) & (0.110) \\ 
  Year (Linear) $\times$ Growing Region & $-$0.001 &  \\ 
  & (0.049) &  \\ 
  1991 $\times$ Growing Region &  & 0.006 \\ 
  &  & (0.156) \\ 
  1992 $\times$ Growing Region &  & $-$0.001 \\ 
  &  & (0.155) \\ 
  1993 $\times$ Growing Region &  & 0.0004 \\ 
  &  & (0.155) \\ 
  Constant & $-$14.693 & $-$8.648$^{***}$ \\ 
  & (49.206) & (0.055) \\ 
 \hline \\[-1.8ex] 
Observations & 4,225 & 4,225 \\ 
F Statistic & 4.577$^{***}$ (df = 3; 4221) & 1.986$^{*}$ (df = 7; 4217) \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{2}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Test if grow×year interactions are jointly zero}
\FunctionTok{linearHypothesis}\NormalTok{(year\_factor, }\FunctionTok{matchCoefs}\NormalTok{(year\_factor, }\StringTok{":grow"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Linear hypothesis test:
## factor(year)1991:grow = 0
## factor(year)1992:grow = 0
## factor(year)1993:grow = 0
## 
## Model 1: restricted model
## Model 2: outcome ~ factor(year) + grow + factor(year):grow
## 
##   Res.Df   RSS Df Sum of Sq     F Pr(>F)
## 1   4220 10162                          
## 2   4217 10162  3 0.0058328 8e-04      1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Graph: Average outcome by year and group}
\NormalTok{dta\_pretreatment }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(year, grow) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{mean\_outcome =} \FunctionTok{mean}\NormalTok{(outcome, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ year, }\AttributeTok{y =}\NormalTok{ mean\_outcome, }\AttributeTok{color =} \FunctionTok{factor}\NormalTok{(grow))) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{size =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{size =} \DecValTok{2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Pre{-}treatment Trends in Violence by Region Type"}\NormalTok{,}
    \AttributeTok{subtitle =} \StringTok{"Checking Parallel Trends (1990–1993)"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Year"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Mean Logged per{-}capita Violent Death Rate"}\NormalTok{,}
    \AttributeTok{color =} \StringTok{"Coca{-}growing Region"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Tutorial-Week-6_files/figure-latex/q4-visual-trends-1.pdf}}

\textbf{Interpretation:}

To assess the validity of the parallel trend assumption, we focused on
the pre-treatment period from 1990 to 1993. Both regression models
formally test this parallel trends assumption by examining if the
pre-treatment trends in violence are statistically different between the
coca-growing regions and non-growing regions. The first model simplifies
our analysis by assuming that time follows a linear trend. The key
coefficient here is the interaction term \textbf{year:grow}, which
measures the difference in the slopes of trend lines for the two groups.
The p-value for this term is 0.99, which indicates that there is no
statistically significant difference between the slopes. The second
model offers a more flexible, year-by-year analysis by checking if the
gap in violence between the two groups changed in any year from 1991 to
1993 compared to the baseline year of 1990, instead of assuming a
straight line. The additional, joint F-test on these interactions yields
a p-value of 1 which is why we fail to reject the null hypothesis
\(H_0\) that the pre-treatment trends are perfectly parallel. This
result is crucial because it validates the use of non-growing regions as
a credible counterfactual. It gives us confidence that any divergence
between the groups after the disruption is due to the coca boom itself,
rather than pre-existing differences in trends.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Q5. Placebo DiD Test}\label{q5.-placebo-did-test}

\textbf{Tasks:}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Create \texttt{placebo\_after} (1 if year \(= 1992\) or \(1993\), 0 if
  year \(= 1990\) or \(1991\))
\item
  Estimate placebo DiD model
\item
  Interpret \texttt{placebo\_after} \(\times\) \texttt{grow} coefficient
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Subset and create placebo variables}
\NormalTok{dta\_placebo }\OtherTok{\textless{}{-}}\NormalTok{ dta }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(year }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\DecValTok{1990}\NormalTok{, }\DecValTok{1991}\NormalTok{, }\DecValTok{1992}\NormalTok{, }\DecValTok{1993}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{grow =} \FunctionTok{ifelse}\NormalTok{(dep\_ocu }\SpecialCharTok{\%in\%}\NormalTok{ department\_list, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{),}
    \AttributeTok{outcome =} \FunctionTok{log}\NormalTok{((violent }\SpecialCharTok{+} \DecValTok{1}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ (populati }\SpecialCharTok{+} \DecValTok{1}\NormalTok{)),}
    \AttributeTok{placebo\_after =} \FunctionTok{ifelse}\NormalTok{(year }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\DecValTok{1992}\NormalTok{, }\DecValTok{1993}\NormalTok{), }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Estimate placebo DiD model}
\NormalTok{placebo\_did }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(outcome }\SpecialCharTok{\textasciitilde{}}\NormalTok{ placebo\_after }\SpecialCharTok{+}\NormalTok{ grow }\SpecialCharTok{+}\NormalTok{ placebo\_after}\SpecialCharTok{:}\NormalTok{grow, }\AttributeTok{data =}\NormalTok{ dta\_placebo)}

\CommentTok{\# Create stargazer table}
\NormalTok{placebo\_labels }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"Placebo \textquotesingle{}After\textquotesingle{} (1992{-}93)"}\NormalTok{,}
  \StringTok{"Coca{-}Growing Region"}\NormalTok{,}
  \StringTok{"Placebo \textquotesingle{}After\textquotesingle{} $}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{times$ Growing Region"}\NormalTok{,}
  \StringTok{"Constant"}
\NormalTok{)}

\CommentTok{\# Run stargazer}
\FunctionTok{stargazer}\NormalTok{(}
\NormalTok{  placebo\_did,}
  \AttributeTok{type =} \StringTok{"latex"}\NormalTok{,}
  \AttributeTok{title =} \StringTok{"Table 2: Placebo Difference{-}in{-}Differences Test"}\NormalTok{,}
  \AttributeTok{header =} \ConstantTok{FALSE}\NormalTok{,}
  \AttributeTok{column.labels =} \StringTok{"Placebo Model"}\NormalTok{,}
  \AttributeTok{dep.var.labels =} \StringTok{"Logged Per{-}Capita Violent Death Rate"}\NormalTok{,}
  \AttributeTok{covariate.labels =}\NormalTok{ placebo\_labels,}
  \AttributeTok{no.space =} \ConstantTok{TRUE}\NormalTok{,}
  \AttributeTok{omit.stat =} \FunctionTok{c}\NormalTok{(}\StringTok{"adj.rsq"}\NormalTok{, }\StringTok{"ser"}\NormalTok{, }\StringTok{"f"}\NormalTok{, }\StringTok{"rsq"}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}[!htbp] \centering 
  \caption{Table 2: Placebo Difference-in-Differences Test} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}}lc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{1}{c}{\textit{Dependent variable:}} \\ 
\cline{2-2} 
\\[-1.8ex] & Logged Per-Capita Violent Death Rate \\ 
 & Placebo Model \\ 
\hline \\[-1.8ex] 
 Placebo 'After' (1992-93) & 0.005 \\ 
  & (0.055) \\ 
  Coca-Growing Region & 0.204$^{***}$ \\ 
  & (0.078) \\ 
  Placebo 'After' $\times$ Growing Region & $-$0.003 \\ 
  & (0.110) \\ 
  Constant & $-$8.636$^{***}$ \\ 
  & (0.039) \\ 
 \hline \\[-1.8ex] 
Observations & 4,225 \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{1}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table}

\textbf{Interpretation:}

In general, the placebo test helps us to check the parallel trends
assumption, stating that the outcome (violence) in the treatment group
(coca-growing regions) and the control group (non-growing regions) would
have developed the same way, had the treatment (air bridge disruption)
not been applied. For that reason, we take only the data from the
``before'' period (1990-1993), when the real treatment (starting 1996)
has not happened yet. Moreover, we invent a fake intervention that
supposedly happened in the middle of this period and split the data in
two halves. We run the same DiD regression using this subset of the
data. As there is no treatment, at least that we know of, applied during
that time, the interaction coefficient \textbf{placebo\_after:grow}
should not be significant. In other words, we do not want to reject the
null hypothesis for this placebo test, as it assumes that in the
pre-treatment period, there was no difference in the trend of violence
between the coca-growing region and the non-growing regions. This serves
as a form of ``sanity check'', to test the credibility of our main DiD
analysis, specifically the underlying parallel trends assumption. A
significant coefficient would, of course, suggest the opposite. Our
results show this coefficient is -0.0031 and indeed not significant with
a p-value of 0.977. This confirms our assumption that the two groups
were trending parallel, giving us confidence that the significant effect
we find later is due to the impact of treatment and not the product of
some pre-existing trend.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Q6. Covariate Balance at Time
0}\label{q6.-covariate-balance-at-time-0}

\textbf{Task:} Compare treatment and control regions on \texttt{age},
\texttt{sex}, and \texttt{populati} using pre-treatment data.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create balance table}
\NormalTok{dta\_balance }\OtherTok{\textless{}{-}}\NormalTok{ dta\_subset }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(after }\SpecialCharTok{==} \DecValTok{0}\NormalTok{)}

\NormalTok{balance\_table }\OtherTok{\textless{}{-}}\NormalTok{ dta\_balance }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(grow) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{mean\_age =} \FunctionTok{mean}\NormalTok{(age, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{mean\_sex =} \FunctionTok{mean}\NormalTok{(sex, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{mean\_pop =} \FunctionTok{mean}\NormalTok{(populati, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  )}

\CommentTok{\# Rename \textquotesingle{}grow\textquotesingle{} for clarity before printing}
\NormalTok{balance\_table }\OtherTok{\textless{}{-}}\NormalTok{ balance\_table }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{grow =} \FunctionTok{ifelse}\NormalTok{(grow }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, }\StringTok{"Growing Region (Treat)"}\NormalTok{, }\StringTok{"Non{-}Growing Region (Control)"}\NormalTok{))}

\CommentTok{\# Table Output }
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(}
\NormalTok{  balance\_table,}
  \AttributeTok{caption =} \StringTok{"Table 3: Covariate Balance in Pre{-}Treatment Period (Time 0)"}\NormalTok{,}
  \AttributeTok{col.names =} \FunctionTok{c}\NormalTok{(}\StringTok{"Region Type"}\NormalTok{, }\StringTok{"Mean Age"}\NormalTok{, }\StringTok{"Mean Sex"}\NormalTok{, }\StringTok{"Mean Population"}\NormalTok{),}
  \AttributeTok{digits =} \DecValTok{2}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrrr@{}}
\caption{Table 3: Covariate Balance in Pre-Treatment Period (Time
0)}\tabularnewline
\toprule\noalign{}
Region Type & Mean Age & Mean Sex & Mean Population \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Region Type & Mean Age & Mean Sex & Mean Population \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Non-Growing Region (Control) & 15.56 & 1.51 & 78300.87 \\
Growing Region (Treat) & 15.46 & 1.59 & 40540.90 \\
\end{longtable}

\textbf{Interpretation:}

In the balance check, we check if the treatment and control groups
looked similar before the treatment started, by grouping the
pre-treatment data into treatment (growing regions) and control group
(non-growing regions) and calculating the mean for the variables age,
sex, and populati . This is critical for DiD validity because the entire
method relies on the assumption that the control group serves as a valid
counterfactual for the treatment group. If the groups already were
different before the treatment, we couldn't be sure if a later change in
violence was due to the treatment (the coca boom) or those pre-existing
differences. This serves as a useful addition to the placebo test. While
in the placebo test, we checked if trends in the outcome (violence) were
already diverging before treatment , the balance check compares the
average levels of group characteristics (like age or population) at the
start, helping us to select a control group that is at least plausibly
similar to the treatment group before the treatment. This is also the
reason why the authors, unfortunately, do not compare the coca-growing
regions in Colombia to Neckarstadt West, as the two groups would be
widely imbalanced on various key characteristics, even if there were
parallel trends in the outcome (logged per-capita violent death rate)
before treatment application. In our results , we can see that age is
almost perfectly balanced (15.5 vs 15.6), and sex is mostly balanced
(1.51 vs 1.59). Regarding populati, we see a large imbalance, where the
treatment regions (40,541) are almost half as populated as the control
regions (78,301). This strongly suggests that coca cultivation didn't
just appear anywhere, but rather ``selected into'' areas that were
already systematically more rural and less populated. Considering that
large imbalance, we would have to worry about it, as we could not rule
out the difference of being more rural as the real reason for a change
in violence and not the treatment. However, looking at our previous
tests, despite the imbalance, the trends in violence were parallel
before the treatment . The authors try to address this issue, by making
the groups more comparable. They drop the departments with the largest
cities (like Bogota) from the control group in their main analysis. So
by making groups slightly more comparable and having secured before that
we have parallel trends before the treatment, we can still be confident
in the analysis.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Q7. Why Covariate Balance
Matters}\label{q7.-why-covariate-balance-matters}

\textbf{Discussion Questions:}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  If covariates are balanced at time 0, what does this imply about
  confounding?
\end{enumerate}

\begin{itemize}
\tightlist
\item
  If our covariates were perfectly balanced, it would imply that the
  selection into the treatment group was ``as good as random''. This
  would be the ideal case, as it would mean that there are no observed
  pre-existing differences (or confounders) that could offer an
  alternative explanation for our results. However, as we saw in our
  balance check , the groups are imbalanced on \textbf{populati}, which
  confirms that selection was not random and we must deal with these
  confounders.
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  What role do these variables play after assignment?
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Since our Q6 check showed that the groups are imbalanced (especially
  on \textbf{populati}), we can't just ignore these differences. Their
  role is to be control variables in our main DiD regression. By adding
  \textbf{age}, \textbf{sex}, and \textbf{populati} to the model, we are
  statistically ``leveling the playing field.'' The regression
  ``partials out'' (or removes) the effect of these confounding
  variables, which ``cleans'' our DiD estimate. This allows us to adjust
  for the fact that the groups weren't identical to begin with, making
  our final after:grow coefficient much more credible.
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  If violence trends already differ before treatment, how might this
  bias DiD?
\end{enumerate}

\begin{itemize}
\tightlist
\item
  This is the most critical threat to our entire study. If the violence
  trends were already different (e.g., if violence in coca regions was
  already increasing faster than in non-growing regions before 1996),
  our DiD model would be biased. The model would falsely attribute that
  pre-existing difference in trends to the ``air bridge'' disruption.
  This would completely mix up the ``fake'' trend effect with the
  ``real'' treatment effect, making our final coefficient meaningless.
  This is precisely why the Q4 and Q5 tests were so vital : they proved
  this wasn't happening, so we can be confident our DiD is not biased in
  this way.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Q8. Covariate Timing and Post-Treatment
Bias}\label{q8.-covariate-timing-and-post-treatment-bias}

\textbf{Discussion Questions:}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Should we include covariates from time 0, time 1, or both?
\end{enumerate}

\begin{itemize}
\tightlist
\item
  For the sake of our difference-in-difference model, we should include
  the covariates measured at Time 0, as well as the time-invariant
  covariates that do not change over time (e.g.~\textbf{sex}). The
  purpose of adding covariates in this context is to control for
  confounding factors. As we discovered in Question 6, the treatment
  (\textbf{grow} = 1) and control (\textbf{grow} = 0) groups were not
  identical at the outset, with the growing regions having much lower
  populations. This creates an issue, as we cannot determine whether the
  DiD effect is due to the coca boom or if rural regions with low
  populations simply have different violence trends naturally. By adding
  covariates such as \textbf{populati} from the baseline period (Time 0)
  to our regression model, we can statistically adjust for this
  pre-existing difference. The model essentially allows us to compare
  the groups as if they had started with the same population levels.
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  What happens if you include a covariate measured after treatment?
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Adding a covariate that is measured after the treatment could lead to
  severe problems. In this case, for example, the treatment (i.e.~the
  coca boom) might have caused a change in the covariate, which in turn
  caused a change in the outcome (violence). Let us break this example
  down: First, we observe the coca boom happening. This boom might cause
  people to move to the region to find work, resulting in a change in
  the population at Time 1. This change in population could then lead to
  more violence. Therefore, this change in population is one of the
  mechanisms through which the coca boom affects violence, and is
  therefore part of the overall causal effect. However, by controlling
  for population in our model at Time 1, we block one of the main ways
  in which the treatment works, as we have instructed the model to
  disregard the fact that a significant aspect of the coca boom's impact
  was its effect on population change. This could lead to a serious
  underestimation of our causal effect. This issue is especially
  important in DiD frameworks, where post-treatment covariates can
  introduce what's known as \textbf{post-treatment bias}, leading to
  highly biased estimates.
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  When might adjusting for post-treatment variables be appropriate?
\end{enumerate}

\begin{itemize}
\tightlist
\item
  If our main goal is to find the total causal effect of the treatment,
  it is almost never appropriate to adjust for such variables. One
  exception is if we are conducting a mediation analysis and
  deliberately change our research question from `What is the total
  effect of the coca boom on violence?' to `How much of the coca boom's
  effect on violence is explained by changes in region's population?'.
  In this specific case, we would run a regression with and without the
  post-treatment \textbf{populati} variable and compare the \(\beta_3\)
  coefficients. The degree to which the coefficient shrinks after adding
  the population variable would be our estimate of the mediated effect.
  But since we are interested in the total causal effect, we must avoid
  using post-treatment variables as controls.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Q9. Computing the DiD
Estimate}\label{q9.-computing-the-did-estimate}

\textbf{Task:} Compute manual DiD estimate.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Mean difference (after {-} before) for grow=1 and grow=0}
\NormalTok{did\_table }\OtherTok{\textless{}{-}}\NormalTok{ dta\_subset }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(grow, after) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{mean\_outcome =} \FunctionTok{mean}\NormalTok{(outcome, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pivot\_wider}\NormalTok{(}\AttributeTok{names\_from =}\NormalTok{ after, }\AttributeTok{values\_from =}\NormalTok{ mean\_outcome, }\AttributeTok{names\_prefix =} \StringTok{"time"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{diff =}\NormalTok{ time1 }\SpecialCharTok{{-}}\NormalTok{ time0)}

\CommentTok{\# DiD estimate: subtract the two}
\NormalTok{did\_estimate }\OtherTok{\textless{}{-}} \FunctionTok{diff}\NormalTok{(did\_table}\SpecialCharTok{$}\NormalTok{diff)}
\NormalTok{did\_estimate}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1970235
\end{verbatim}

\textbf{Interpretation:}

The problem with a simple before-and-after comparison is that it is
based on the flawed assumption that the only thing that changed for
coca-growing regions between the `before' and `after' periods was the
disruption to the air bridge. However, it is almost certain that other
trends were at play during that time that could have caused changes in
violence rates across the entire country, which were completely
unrelated to the coca boom. For example, if violence was generally
increasing across all of Colombia due to political instability or
economic problems, a simple before-after comparison in the growing
regions would wrongly attribute all of that increase to the coca boom,
unable to distinguish between the effects of the treatment and those of
other confounding trends occurring simultaneously.

By contrast, the difference-in-differences (DiD) estimate is superior
because it uses non-growing regions (\textbf{grow} = 0) as a
counterfactual to address this issue. The logic is that the difference
between the `after' and `before' periods in the non-growing regions acts
as a benchmark, essentially capturing the change in violence due to all
those other nationwide factors. The difference in the growing regions,
however, captures the same `background trend' plus the true causal
effect of the coca boom. By subtracting the control group's change from
the treatment group's change, we can effectively control for the
background trend, provided the crucial parallel trends assumption holds
(which our Q4 and Q5 tests suggest it does ). This isolates the true
causal effect.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Q10. Regression Form of DiD}\label{q10.-regression-form-of-did}

\textbf{Tasks:}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Estimate: outcome
  \(= \beta_0 + \beta_1 \cdot \text{after} + \beta_2 \cdot \text{grow} + \beta_3 \cdot (\text{after} \times \text{grow}) + u\)
\item
  Report \(\beta_3\) and p-value
\item
  Show analytically that \(\beta_3\) equals the manual DiD estimate
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# DiD regression model}
\NormalTok{did }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(outcome }\SpecialCharTok{\textasciitilde{}}\NormalTok{ after }\SpecialCharTok{+}\NormalTok{ grow }\SpecialCharTok{+}\NormalTok{ after}\SpecialCharTok{:}\NormalTok{grow, }\AttributeTok{data =}\NormalTok{ dta\_subset)}

\NormalTok{did\_labels }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"After Period (1996{-}98)"}\NormalTok{,}
  \StringTok{"Coca{-}Growing Region"}\NormalTok{,}
  \StringTok{"After Period $}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{times$ Growing Region"}\NormalTok{,}
  \StringTok{"Constant"}
\NormalTok{)}

\CommentTok{\# Run stargazer}
\FunctionTok{stargazer}\NormalTok{(}
\NormalTok{  did,}
  \AttributeTok{type =} \StringTok{"latex"}\NormalTok{,}
  \AttributeTok{title =} \StringTok{"Table 4: Main Difference{-}in{-}Differences Estimate of Coca Boom on Violence"}\NormalTok{,}
  \AttributeTok{header =} \ConstantTok{FALSE}\NormalTok{,}
  \AttributeTok{column.labels =} \StringTok{"DiD Model"}\NormalTok{,}
  \AttributeTok{dep.var.labels =} \StringTok{"Logged Per{-}Capita Violent Death Rate"}\NormalTok{,}
  \AttributeTok{covariate.labels =}\NormalTok{ did\_labels,}
  \AttributeTok{no.space =} \ConstantTok{TRUE}\NormalTok{,}
  \AttributeTok{omit.stat =} \FunctionTok{c}\NormalTok{(}\StringTok{"adj.rsq"}\NormalTok{, }\StringTok{"ser"}\NormalTok{, }\StringTok{"f"}\NormalTok{, }\StringTok{"rsq"}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}[!htbp] \centering 
  \caption{Table 4: Main Difference-in-Differences Estimate of Coca Boom on Violence} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}}lc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{1}{c}{\textit{Dependent variable:}} \\ 
\cline{2-2} 
\\[-1.8ex] & Logged Per-Capita Violent Death Rate \\ 
 & DiD Model \\ 
\hline \\[-1.8ex] 
 After Period (1996-98) & $-$0.141$^{***}$ \\ 
  & (0.045) \\ 
  Coca-Growing Region & 0.203$^{***}$ \\ 
  & (0.063) \\ 
  After Period $\times$ Growing Region & 0.197$^{**}$ \\ 
  & (0.088) \\ 
  Constant & $-$8.628$^{***}$ \\ 
  & (0.032) \\ 
 \hline \\[-1.8ex] 
Observations & 6,449 \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{1}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table}

\textbf{Interpretation:} The \(\beta_3\) coefficient of our interaction
term \textbf{after:grow} is 0.19702 with a p-value of 0.0256. Since the
p-value is less than 0.05, the effect is statistically significant,
which means that the effect of 0.19072 is not just a random fluctuation.
After controlling for pre-existing differences between the regions
(\textbf{grow}) and for general time trends affecting all of Colombia
(\textbf{after}), the air-bridge disruption caused a significant
increase in the logged per-capita violent death rate of 0.197 in the
coca growing regions.

\newpage

\textbf{Analytical proof:}

We want to show that \(\beta_3\) in the regression model represents the
Difference-in-Differences (DiD) estimate. Let \(Y\) be the outcome,
\(G\) be the treatment group indicator (\(G=1\) for \texttt{grow}, 0
otherwise), and \(P\) be the post-treatment period indicator (\(P=1\)
for \texttt{after}, 0 otherwise).

The regression model is: \[
Y = \beta_0 + \beta_1 P + \beta_2 G + \beta_3 (P \times G) + u
\] The expected value of the outcome \(Y\) conditional on the group and
period is: \[
E[Y | G, P] = \beta_0 + \beta_1 P + \beta_2 G + \beta_3 (P \times G)
\] This gives us the expected value for each of the four groups:

\begin{itemize}
\tightlist
\item
  \textbf{Control, Before (\(G=0, P=0\)):} \(E[Y | G=0, P=0] = \beta_0\)
\item
  \textbf{Control, After (\(G=0, P=1\)):}
  \(E[Y | G=0, P=1] = \beta_0 + \beta_1\)
\item
  \textbf{Treatment, Before (\(G=1, P=0\)):}
  \(E[Y | G=1, P=0] = \beta_0 + \beta_2\)
\item
  \textbf{Treatment, After (\(G=1, P=1\)):}
  \(E[Y | G=1, P=1] = \beta_0 + \beta_1 + \beta_2 + \beta_3\)
\end{itemize}

The DiD parameter, let's call it \(\delta\), is defined as the
difference in the ``after-before'' change for the treatment group and
the ``after-before'' change for the control group:

\[
\delta = \Big( E[Y | G=1, P=1] - E[Y | G=1, P=0] \Big) - \Big( E[Y | G=0, P=1] - E[Y | G=0, P=0] \Big)
\] Now, we substitute the regression coefficients into this formula:

\begin{align*}
\delta &= \Big( (\beta_0 + \beta_1 + \beta_2 + \beta_3) - (\beta_0 + \beta_2) \Big) - \Big( (\beta_0 + \beta_1) - \beta_0 \Big) \\
&= \Big( \beta_1 + \beta_3 \Big) - \Big( \beta_1 \Big) \\
&= \beta_3
\end{align*} ---

\section{Q11. Adding Covariates}\label{q11.-adding-covariates}

\textbf{Task:} Estimate three models and compare.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Model 1: outcome \textasciitilde{} grow + after + growafter}
\NormalTok{cov\_did1 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(outcome }\SpecialCharTok{\textasciitilde{}}\NormalTok{ after }\SpecialCharTok{+}\NormalTok{ grow }\SpecialCharTok{+}\NormalTok{ after}\SpecialCharTok{:}\NormalTok{grow, }\AttributeTok{data =}\NormalTok{ dta\_subset)}

\CommentTok{\# Model 2: Add age and sex}
\NormalTok{cov\_did2 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(outcome }\SpecialCharTok{\textasciitilde{}}\NormalTok{ after }\SpecialCharTok{+}\NormalTok{ grow }\SpecialCharTok{+}\NormalTok{ after}\SpecialCharTok{:}\NormalTok{grow }\SpecialCharTok{+}\NormalTok{ age }\SpecialCharTok{+}\NormalTok{ sex, }\AttributeTok{data =}\NormalTok{ dta\_subset)}

\CommentTok{\# Model 3: Add age, sex, and populati}
\NormalTok{cov\_did3 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(outcome }\SpecialCharTok{\textasciitilde{}}\NormalTok{ after }\SpecialCharTok{+}\NormalTok{ grow }\SpecialCharTok{+}\NormalTok{ after}\SpecialCharTok{:}\NormalTok{grow }\SpecialCharTok{+}\NormalTok{ age }\SpecialCharTok{+}\NormalTok{ sex }\SpecialCharTok{+}\NormalTok{ populati, }\AttributeTok{data =}\NormalTok{ dta\_subset)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Compare models}
\FunctionTok{stargazer}\NormalTok{(cov\_did1, cov\_did2, cov\_did3,     }
          \AttributeTok{type =} \StringTok{"latex"}\NormalTok{,                 }
          \AttributeTok{title =} \StringTok{"Regression Results: The Effect of Treatment on Outcome"}\NormalTok{,}
          \AttributeTok{align =} \ConstantTok{TRUE}\NormalTok{,                   }
          \AttributeTok{dep.var.labels =} \StringTok{"Outcome"}\NormalTok{,     }
          \AttributeTok{column.labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Base Model"}\NormalTok{, }\StringTok{"Adds Demographics"}\NormalTok{, }\StringTok{"Full Model"}\NormalTok{),}
          \AttributeTok{covariate.labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"After Treatment"}\NormalTok{, }\StringTok{"Treatment Group (Grow)"}\NormalTok{, }\StringTok{"Age"}\NormalTok{,}
                               \StringTok{"Sex"}\NormalTok{, }\StringTok{"Population"}\NormalTok{, }\StringTok{"Interaction: After x Grow"}\NormalTok{),}
          \AttributeTok{notes =} \StringTok{"Standard errors are in parentheses."}\NormalTok{,}
          \AttributeTok{notes.align =} \StringTok{"l"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy
Institute. E-mail: marek.hlavac at gmail.com \% Date and time: Sa, Okt
25, 2025 - 13:15:24 \% Requires LaTeX packages: dcolumn

\begin{table}[!htbp] \centering 
  \caption{Regression Results: The Effect of Treatment on Outcome} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} } 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\ 
\cline{2-4} 
\\[-1.8ex] & \multicolumn{3}{c}{Outcome} \\ 
 & \multicolumn{1}{c}{Base Model} & \multicolumn{1}{c}{Adds Demographics} & \multicolumn{1}{c}{Full Model} \\ 
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\ 
\hline \\[-1.8ex] 
 After Treatment & -0.141^{***} & -0.123^{***} & -0.107^{***} \\ 
  & (0.045) & (0.036) & (0.036) \\ 
  & & & \\ 
 Treatment Group (Grow) & 0.203^{***} & 0.304^{***} & 0.231^{***} \\ 
  & (0.063) & (0.051) & (0.051) \\ 
  & & & \\ 
 Age &  & 0.142^{***} & 0.123^{***} \\ 
  &  & (0.003) & (0.004) \\ 
  & & & \\ 
 Sex &  & -1.057^{***} & -1.057^{***} \\ 
  &  & (0.028) & (0.028) \\ 
  & & & \\ 
 Population &  &  & -0.00000^{***} \\ 
  &  &  & (0.00000) \\ 
  & & & \\ 
 Interaction: After x Grow & 0.197^{**} & 0.131^{*} & 0.123^{*} \\ 
  & (0.088) & (0.071) & (0.071) \\ 
  & & & \\ 
 Constant & -8.628^{***} & -9.162^{***} & -8.731^{***} \\ 
  & (0.032) & (0.070) & (0.079) \\ 
  & & & \\ 
\hline \\[-1.8ex] 
Observations & \multicolumn{1}{c}{6,449} & \multicolumn{1}{c}{6,449} & \multicolumn{1}{c}{6,449} \\ 
R$^{2}$ & \multicolumn{1}{c}{0.009} & \multicolumn{1}{c}{0.350} & \multicolumn{1}{c}{0.363} \\ 
Adjusted R$^{2}$ & \multicolumn{1}{c}{0.008} & \multicolumn{1}{c}{0.350} & \multicolumn{1}{c}{0.362} \\ 
Residual Std. Error & \multicolumn{1}{c}{1.550 (df = 6445)} & \multicolumn{1}{c}{1.256 (df = 6443)} & \multicolumn{1}{c}{1.244 (df = 6442)} \\ 
F Statistic & \multicolumn{1}{c}{19.298$^{***}$ (df = 3; 6445)} & \multicolumn{1}{c}{693.978$^{***}$ (df = 5; 6443)} & \multicolumn{1}{c}{610.532$^{***}$ (df = 6; 6442)} \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{3}{l}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
 & \multicolumn{3}{l}{Standard errors are in parentheses.} \\ 
\end{tabular} 
\end{table}

\textbf{Discussion:} Looking at our final regression table, we can see
that the \(\beta_3\) coefficient - our interaction coefficient: After x
Grow - changes substantially as we add covariates. The estimate
decreases from 0.197 in the simple difference-in-difference (DiD) model
(Model 1) to 0.131 after demographics are added (Model 2), finally
settling at 0.123 in the full model (Model 3). This reduction in the
effect clearly suggests that our simple model was subject to omitted
variable bias, as it attributed some of the effect of demographics and
population to the coca boom. By adding all the covariates to the final
model (Model 3), we can isolate the true effect more accurately.
Therefore, Model 3 seems to be the most credible specification, as it
includes all the covariates that we identified as important and
imbalanced at baseline. Our most reliable estimate of the causal effect
of the air-bridge disruption is an increase of 0.123 in the logged per
capita violent death rate, which is statistically significant at the
10\% level. We can also see that the covariates are incredibly strong
predictors. Simply by adding \textbf{age} and \textbf{sex} in Model 2
causes the \(R^2\) to jump from \(0.9\%\) to \(35\%\).

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Q12. Interpretation and
Reflection}\label{q12.-interpretation-and-reflection}

\textbf{Summary:}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Did violence increase or decrease after the air-bridge disruption?
\item
  Does the evidence support a ``resource-curse'' interpretation?
\item
  What are the remaining identification threats?
\end{enumerate}

{[}Your final interpretation here{]}

\end{document}
